[package]
name = "lib"
version = "0.1.0"
edition = "2024_07"
cairo_version = "2.8.0"

[dependencies]
starknet = "2.8.0"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.15.0" }

[[target.starknet-contract]]
sierra = true
casm = true

[cairo]
sierra-replace-ids = true
